#' Statistical coverage depth distribution
#'
#' This function will calculate the coverage depth distribution of every sample,
#' and generate <outPrefix>.depth_density.pdf and <outPrefix>.depth_density.png.
#'
#' @param x A QTLseq object generated by select_sample_and_SNP().
#' @param outPrefix The prefix of output figure.
#'
#' @return NULL
#' @export
#'
#' @examples
#' library(easyQTLseq)
#' # Example with sample data from a GATK table.
#' file_path <- system.file("extdata", "subset.table.gz", package = "easyQTLseq")
#' # readr::read_tsv() has a faster speed than read.table() when reading a file.
#' data <- readr::read_tsv(file = file_path)
#' x <- select_sample_and_SNP(data = data, highP = "qY", lowP = "R3", highB = "Y", lowB = "R", popType = "F2", bulkSize = c(30, 30))
#' depth_statistics(x = x, outPrefix = "outprefix")

depth_statistics <- function(x, ...) {
  UseMethod("depth_statistics")
}

#' @rdname depth_statistics
#' @export
depth_statistics.QTLseq <- function(x, outPrefix){
  # 统计个样本的DP分布密度
  dp <- x$data %>% select(HP = any_of("HP.DP"), LP = any_of("LP.DP"), HB = HB.DP, LB = LB.DP) %>%
    gather(key = "sample", value = "depth")
  if (all(c("HP", "LP") %in% dp$sample)) {
    dp$sample <- factor(dp$sample, levels = c("HP", "LP", "HB", "LB"), labels = c(x$highP, x$lowP, x$highB, x$lowB))
  } else if ("HP" %in% dp$sample) {
    dp$sample <- factor(dp$sample, levels = c("HP", "HB", "LB"), labels = c(x$highP, x$highB, x$lowB))
  } else if ("LP" %in% dp$sample) {
    dp$sample <- factor(dp$sample, levels = c("LP", "HB", "LB"), labels = c(x$lowP, x$highB, x$lowB))
  } else {
    dp$sample <- factor(dp$sample, levels = c("HB", "LB"), labels = c(x$highB, x$lowB))
  }
  upper <- dp %>% group_by(sample) %>% summarise(ave = mean(depth), sd = sd(depth)) %>% mutate(upper = ave+6*sd) %>% pull(upper) %>% max()
  P_dp <- ggplot(dp, aes(x = depth)) +
    geom_histogram(aes(y = after_stat(density), fill = sample), binwidth = 2) +
    geom_density() +
    scale_x_continuous(limits = c(0, upper)) +
    theme_half_open() +
    facet_wrap(~sample, nrow = 1)
  if (length(unique(dp$sample)) == 4) {
    ggsave(P_dp, filename = paste(outPrefix, "depth_density.pdf", sep = "."), height = 3.5, width = 12)
    ggsave(P_dp, filename = paste(outPrefix, "depth_density.png", sep = "."), height = 3.5, width = 12, dpi = 500)
  } else if (length(unique(dp$sample)) == 3) {
    ggsave(P_dp, filename = paste(outPrefix, "depth_desity.pdf", sep = "."), height = 3.5, width = 10)
    ggsave(P_dp, filename = paste(outPrefix, "depth_desity.png", sep = "."), height = 3.5, width = 10, dpi = 500)
  } else if (length(unique(dp$sample)) == 2) {
    ggsave(P_dp, filename = paste(outPrefix, "depth_density.pdf", sep = "."), height = 3.5, width = 6)
    ggsave(P_dp, filename = paste(outPrefix, "depth_density.png", sep = "."), height = 3.5, width = 6, dpi = 500)
  }
}
